# Generated by Django 4.2.7 on 2024-05-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_alter_cliente_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_visita',
        ),
    ]
