# Generated by Django 4.2.7 on 2024-05-28 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0005_remove_cliente_data_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.cliente')),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_status', to='calendarapp.status')),
                ('old_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_status', to='calendarapp.status')),
            ],
        ),
    ]
